name: haircut_express
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  
  # Firebase (Versi Kompatibel Terbaru)
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  
  # TAMBAHAN UNTUK UPLOAD FOTO PROFIL
  firebase_storage: ^12.3.2  # Menyimpan file foto di Firebase
  image_picker: ^1.1.2     # Memilih foto dari Galeri/Kamera
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Notifications (Local)
  flutter_local_notifications: ^18.0.1
  
  # Utilities
  intl: ^0.19.0
  google_fonts: ^6.2.1
  
  # Optional
  table_calendar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Folder aset (pastikan folder assets/images/ sudah dibuat)
  assets:
    - assets/images/