name: haircut_expres
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # >>> DEPENDENCIES BARU UNTUK KALENDER DAN API <<<
  table_calendar: ^3.0.9      # Untuk UI kalender interaktif
  googleapis: ^12.0.0         # Untuk mengambil data dari Google Calendar API
  googleapis_auth: ^1.4.0      # Untuk otentikasi API
  http: ^1.6.0
  # -----------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# ... (Sisa kode flutter: dan konfigurasi lainnya)

flutter:
  uses-material-design: true